import { MailboxRecord, WarmupProfile } from './MailboxTypes';

export const DEFAULT_WARMUP_PROFILE: WarmupProfile = {
  id: 'default_google_workspace_gradual',
  name: 'Google Workspace Safety Ramp-up',
  maxBounceRatePercent: 2.5,
  maxSpamRatePercent: 0.1,
  stages: [
    { dayMin: 1, dayMax: 3, dailyLimit: 10, stage: 'stage_1' },
    { dayMin: 4, dayMax: 7, dailyLimit: 15, stage: 'stage_2' },
    { dayMin: 8, dayMax: 14, dailyLimit: 20, stage: 'stage_3' },
    { dayMin: 15, dayMax: 21, dailyLimit: 30, stage: 'stage_4' },
    { dayMin: 22, dayMax: 28, dailyLimit: 40, stage: 'stage_5' },
    { dayMin: 29, dayMax: 999, dailyLimit: 50, stage: 'graduated' },
  ],
};

export const DEFAULT_MAILBOXES: MailboxRecord[] = [
  {
    id: 'mb_jason',
    email: 'jason@ajandco.site',
    displayName: 'Jason | AJ & Co.',
    status: 'healthy',
    warmupDay: 18,
    warmupStage: 'stage_4',
    currentDailyLimit: 30,
    todaySentCount: 14,
    remainingCapacity: 16,
    replyCount: 9,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 98,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_amaan',
    email: 'amaan@ajandco.site',
    displayName: 'Amaan | AJ & Co.',
    status: 'healthy',
    warmupDay: 18,
    warmupStage: 'stage_4',
    currentDailyLimit: 30,
    todaySentCount: 12,
    remainingCapacity: 18,
    replyCount: 7,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 96,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_hello',
    email: 'hello@ajandco.site',
    displayName: 'AJ & Co. Hello',
    status: 'warming',
    warmupDay: 6,
    warmupStage: 'stage_2',
    currentDailyLimit: 15,
    todaySentCount: 5,
    remainingCapacity: 10,
    replyCount: 2,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 92,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_info',
    email: 'info@ajandco.site',
    displayName: 'AJ & Co. Info',
    status: 'warming',
    warmupDay: 4,
    warmupStage: 'stage_2',
    currentDailyLimit: 15,
    todaySentCount: 3,
    remainingCapacity: 12,
    replyCount: 1,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 90,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_contact',
    email: 'contact@ajandco.site',
    displayName: 'AJ & Co. Team',
    status: 'warming',
    warmupDay: 2,
    warmupStage: 'stage_1',
    currentDailyLimit: 10,
    todaySentCount: 2,
    remainingCapacity: 8,
    replyCount: 0,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 88,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
