import { MailboxRecord, WarmupProfile } from './MailboxTypes';

export const DEFAULT_WARMUP_PROFILE: WarmupProfile = {
  id: 'default_google_workspace_gradual',
  name: 'Google Workspace Safety Ramp-up',
  maxBounceRatePercent: 2.5,
  maxSpamRatePercent: 0.1,
  stages: [
    { dayMin: 1, dayMax: 3, dailyLimit: 10, stage: 'stage_1' },
    { dayMin: 4, dayMax: 7, dailyLimit: 15, stage: 'stage_2' },
    { dayMin: 8, dayMax: 14, dailyLimit: 20, stage: 'stage_3' },
    { dayMin: 15, dayMax: 21, dailyLimit: 30, stage: 'stage_4' },
    { dayMin: 22, dayMax: 28, dailyLimit: 40, stage: 'stage_5' },
    { dayMin: 29, dayMax: 999, dailyLimit: 50, stage: 'graduated' },
  ],
};

export const DEFAULT_MAILBOXES: MailboxRecord[] = [
  {
    id: 'mb_1',
    email: 'amaan@ajandco.site',
    displayName: 'Amaan (Founder)',
    status: 'healthy',
    warmupDay: 30,
    warmupStage: 'graduated',
    currentDailyLimit: 50,
    todaySentCount: 14,
    remainingCapacity: 36,
    replyCount: 8,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 99,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_2',
    email: 'outreach@ajandco.site',
    displayName: 'Outreach Inbox 1',
    status: 'healthy',
    warmupDay: 28,
    warmupStage: 'stage_5',
    currentDailyLimit: 40,
    todaySentCount: 11,
    remainingCapacity: 29,
    replyCount: 5,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 97,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_3',
    email: 'growth@ajandco.site',
    displayName: 'Growth Inbox 2',
    status: 'healthy',
    warmupDay: 25,
    warmupStage: 'stage_5',
    currentDailyLimit: 40,
    todaySentCount: 9,
    remainingCapacity: 31,
    replyCount: 4,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 96,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_4',
    email: 'hello@ajandco.site',
    displayName: 'Hello Inbox 3',
    status: 'healthy',
    warmupDay: 21,
    warmupStage: 'stage_4',
    currentDailyLimit: 30,
    todaySentCount: 7,
    remainingCapacity: 23,
    replyCount: 3,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 95,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mb_5',
    email: 'partners@ajandco.site',
    displayName: 'Partners Inbox 4',
    status: 'healthy',
    warmupDay: 18,
    warmupStage: 'stage_4',
    currentDailyLimit: 30,
    todaySentCount: 6,
    remainingCapacity: 24,
    replyCount: 2,
    bounceCount: 0,
    spamComplaints: 0,
    healthScore: 94,
    googleAccountConnected: true,
    oauthStatus: 'connected',
    lastActivity: new Date().toISOString(),
    spfStatus: 'pass',
    dkimStatus: 'pass',
    dmarcStatus: 'pass',
    connectionStatus: 'online',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
